### PR TITLE
replace TravisCI with GitHub Actions CI

### PR DESCRIPTION
**Pull request by sullis**
image

image

image

### CODE REVIEW

**Comment by arakelian** [comment]
@sullis I appreciate the PRs.  Will review and merge within a day or two.  Work has been crazy.

**Comment by sullis** [comment]
@arakelian can you merge this?

**Comment by arakelian** [comment]
@sullis Reviewing now.

**Comment by arakelian** [comment]
@sullis Okay I'm willing to try this out.

**Pull request merged**
